#ifndef QSLIDINGWINDOWCONSUME_GLOBAL_H
#define QSLIDINGWINDOWCONSUME_GLOBAL_H

//#include <QtCore/qglobal.h>

#if defined(QSLIDINGWINDOWCONSUME_LIBRARY)
#  define QSLIDINGWINDOWCONSUMESHARED_EXPORT Q_DECL_EXPORT
#else
#  define QSLIDINGWINDOWCONSUMESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QSLIDINGWINDOWCONSUME_GLOBAL_H
